[window]
  padding = { x = 4, y = 4}
  dynamic_padding = true

[font]
  normal = { family = "FantasqueSans M Nerd Font Mono" }
  bold = { family = "FantasqueSans M Nerd Font Mono" }
  italic = { family = "FantasqueSans M Nerd Font Mono" }
  bold_italic = { family = "FantasqueSans M Nerd Font Mono" }
  size = 7.5
  offset = { x = 0, y = 0 }

[env]
  TERM = "alacritty"

[cursor]
  style = { shape = "Block", blinking = "Always" }
  blink_interval = 500

[mouse]
  hide_when_typing = true

[selection]
  save_to_clipboard = true
